//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFEventAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventActivity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventActivity()
        {
            this.EventActivitySpeakers = new HashSet<EventActivitySpeaker>();
        }
    
        public int EventActivityID { get; set; }
        public Nullable<System.TimeSpan> ActivityStartTime { get; set; }
        public Nullable<System.TimeSpan> ActivityEndTime { get; set; }
        public string ActivityTitle { get; set; }
        public string ActivityLocation { get; set; }
        public string ActivityDesc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventActivitySpeaker> EventActivitySpeakers { get; set; }
    }
}
