//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFEventAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventGuest
    {
        public int EventGuestID { get; set; }
        public Nullable<int> EventID { get; set; }
        public Nullable<int> GuestID { get; set; }
        public Nullable<int> GuestStatusID { get; set; }
        public Nullable<int> DietaryRequirementID { get; set; }
        public string GuestQRCode { get; set; }
    
        public virtual DietaryRequirement DietaryRequirement { get; set; }
        public virtual Event Event { get; set; }
        public virtual Guest Guest { get; set; }
        public virtual GuestStatu GuestStatu { get; set; }
    }
}
