//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFEventAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventActivitySpeaker
    {
        public int SpeakerID { get; set; }
        public Nullable<int> EventEmployeeID { get; set; }
        public Nullable<int> EventActivityID { get; set; }
    
        public virtual EventActivity EventActivity { get; set; }
        public virtual EventEmployee EventEmployee { get; set; }
    }
}
